# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
            WANGARDEN\UserBundle\Entity\User: plaintext
            Symfony\Component\Security\Core\User\User: plaintext
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                     amine:
                         password: aminee

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # On crée un pare-feu uniquement pour le formulaire

        main: # nom du parfeu ou firewalls #
              pattern:      ^/ # pour cacher les url commencent par /#
              anonymous:    true
              provider:     in_memory
              form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
              logout:
                path:       fos_user_security_logout #nom de la route de le déconnexions#
                target:     logout #nom de la route après déconnexion#
              remember_me:
                secret:     %secret% # %secret% est un paramètre de parameter
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN } # toute les pages qui commencent par admin/ sont accessible via le ROLE_ADMIN#
