<?php

namespace WANGARDEN\FactureBundle\Repository;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFactureBy($data)
    {
        $query=$this
    ->createQueryBuilder('a')
            //->addSelect('a.id as id, count(a.id) as nb')
    ->innerJoin('a.client', 'cl')
        //->addselect('COUNT(a)')


    ->addSelect('cl')

          ->add('orderBy', 'cl.nom','nb DESC')

        ;



       /* $qb = $this->em->createQueryBuilder();
        $qb->select('gs.championId as championId, count(gs.id) as nb, sum(gs.win) as wins');
        $qb->from(':GameSummoner','gs');
        $qb->leftJoin('gs.game', 'g');
        $qb->where('gs.summoner=:summonerID');
        $qb->setParameter('summonerID', $summonerID);
        $qb->add('groupBy', 'gs.championId');
        $qb->add('orderBy', 'nb DESC');
*/




//$query->getQuery()->getScalarResult();

        if (is_array($data)) {

      //ID
            if (array_key_exists('id', $data)
        && $data['id']!=null) {
                $query->where('a.id  = :idClient')
            ->setParameter('idCLient', $data['id']);
            }

            //Prénom
            if (array_key_exists('prenom', $data)
          && $data['prenom']!=null) {
                $query->andWhere('cl.prenom LIKE \''.$data['prenom'].'\'');
            }

            //Nom
            if (array_key_exists('nom', $data)
          && $data['nom']!=null) {
                $query->andWhere('cl.nom LIKE \''.$data['nom'].'\'');
            }
        }

        //  ->andwhere('a.id')
//      ->andwhere('a.nom LIKE \''.$nom.'\'')
//      ->setParameters(array('prenom'=>$data['prenom'], 'id'=>$data['id'], 'nom'=>$data['nom']));
        /*  if($data['prenom'] !=''){
            $query->setParameter('prenom'=>$data['prenom']);

          }*/
        return $query->getQuery()->getResult();
    }
}
