<?php

namespace WANGARDEN\FactureBundle\Repository;

/**
 * FactureProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureProduitRepository extends \Doctrine\ORM\EntityRepository
{

    public function factureBy($id)
    {
        $query=$this
            ->createQueryBuilder('a')
            ->Join('a.Facture', 'f')
            ->addSelect('f')
            ->Join('a.produit', 'p')
            ->addSelect('p')
            ->Join('f.client', 'cl')
            ->addSelect('cl')
            ->where('f.id =:id ')
            ->setParameter('id', $id)
        ;

        return $query->getQuery()->getResult();
    }
}
