
wangarden_facture_produit_index:
    path:     /index
    defaults:
      _controller: WANGARDENFactureBundle:Produit:index

wangarden_facture_produit_create:
    path:     /create
    defaults:
      _controller: WANGARDENFactureBundle:Produit:create

wangarden_facture_produit_edit:
    path:     /edit/{id}
    defaults:
      _controller: WANGARDENFactureBundle:Produit:edit

wangarden_facture_produit_supprimer:
    path:     /delete/{id}
    defaults:
      _controller: WANGARDENFactureBundle:Produit:delete
